[package]
name = "spoonrl"
version = "0.1.0"
edition = "2024"
description = "Bigger Spoon RL"

[features]
default = ["native"]
web = ["dep:webatui", "dep:web-sys", "dep:yew"]
native = ["dep:crossterm", "ratatui/crossterm"]

[dependencies]
webatui = { version = "0.1.1", optional = true }
ratatui = { version = "0.25", default-features = false, features = ["all-widgets"] }
crossterm = { version = "0.27", optional = true }
web-sys = { version = "0.3", optional = true, features = [
    "Window",
    "EventTarget",
    "KeyboardEvent",
    "Document",
    "HtmlElement",
    "CssStyleDeclaration",
    "Location"
] }
yew = { version = "0.21", optional = true, default-features = false }
base16-palettes = { version = "0.1.0", features = ["material"] }
